# Generated by Django 4.0.1 on 2022-02-19 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advanced_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.PositiveIntegerField()),
                ('month', models.CharField(max_length=100)),
                ('fdate', models.DateField(auto_now_add=True)),
                ('ftime', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='product/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('fdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='staff/')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('fdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timeing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateField(auto_now_add=True, max_length=100)),
                ('in_time', models.TimeField(auto_now_add=True)),
                ('out_date', models.DateField(auto_now=True, max_length=100)),
                ('out_time', models.TimeField(auto_now=True)),
                ('fdate', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.staff')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='service/')),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('cost', models.PositiveIntegerField()),
                ('fdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.PositiveIntegerField()),
                ('extra', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('month', models.CharField(max_length=100)),
                ('fdate', models.DateField(auto_now_add=True)),
                ('ftime', models.TimeField(auto_now_add=True)),
                ('advance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.advanced_salary')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.staff')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.PositiveBigIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('fdate', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Local_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.PositiveBigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('staff', models.CharField(blank=True, max_length=100, null=True)),
                ('datex', models.DateField(max_length=100)),
                ('timex', models.TimeField()),
                ('fdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gall', models.ImageField(upload_to='gallery/')),
                ('fdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.PositiveBigIntegerField()),
                ('feed', models.TextField(max_length=1400)),
                ('fdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.CharField(max_length=100)),
                ('phone', models.PositiveBigIntegerField()),
                ('datex', models.DateField(max_length=100)),
                ('timex', models.TimeField()),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('fdate', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.staff')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.CharField(max_length=100)),
                ('phone', models.PositiveBigIntegerField()),
                ('datex', models.DateField(max_length=100)),
                ('timex', models.TimeField()),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('fdate', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.staff')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='advanced_salary',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.staff'),
        ),
        migrations.AddField(
            model_name='advanced_salary',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
