# Generated by Django 4.0.1 on 2022-03-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeing',
            name='tell',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
