# Generated by Django 4.0.1 on 2022-03-14 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0002_timeing_tell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fack', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(max_length=100)),
                ('qty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.PositiveBigIntegerField()),
                ('special', models.PositiveIntegerField(blank=True, null=True)),
                ('fdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.PositiveBigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('advance', models.PositiveIntegerField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('fdate', models.DateTimeField(auto_now_add=True)),
                ('pk_names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.create_packages')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('fdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='My_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust', models.CharField(blank=True, max_length=100, null=True)),
                ('fack', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(max_length=100)),
                ('qty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.PositiveBigIntegerField()),
                ('special', models.PositiveIntegerField(blank=True, null=True)),
                ('fdate', models.DateTimeField(auto_now_add=True)),
                ('customers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.customers_package')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='create_packages',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.package_name'),
        ),
        migrations.AddField(
            model_name='create_packages',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
