# Generated by Django 4.0.1 on 2022-03-24 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_create_packages_customers_package_package_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers_package',
            name='pk_names',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.package_name'),
        ),
    ]
