# Generated by Django 4.0.1 on 2022-03-24 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_customers_package_pk_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='pro_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.product'),
        ),
    ]
