# Generated by Django 4.0.1 on 2022-03-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_my_package_find'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_package',
            name='find',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
