# Generated by Django 4.0.1 on 2022-02-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_extend_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extend_access',
            name='ex_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='extend_access',
            name='ex_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='extend_access',
            name='set_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='extend_access',
            name='set_time',
            field=models.CharField(max_length=100),
        ),
    ]
